/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdea8',
        'outline-variant': '#4d4637',
        'on-secondary': '#15305a',
        background: '#001633',
        'surface-tint': '#eac25c',
        'inverse-primary': '#765a00',
        'on-secondary-container': '#9eb5e8',
        'secondary-container': '#2e4672',
        'on-surface-variant': '#d1c5b1',
        'surface-container-highest': '#2b3549',
        'surface-dim': '#001633',
        'on-tertiary-fixed': '#271900',
        surface: '#001633',
        'on-tertiary': '#422d00',
        'surface-container-lowest': '#001633',
        'surface-container-high': '#202a3e',
        'surface-variant': '#2b3549',
        secondary: '#afc7fa',
        'surface-container-low': '#001633',
        'tertiary-fixed-dim': '#febb29',
        'on-primary-fixed-variant': '#594400',
        'primary-fixed-dim': '#eac25c',
        error: '#ffb4ab',
        outline: '#99907d',
        'primary-container': '#e8c05a',
        'surface-container': '#161f33',
        'primary-fixed': '#ffdf95',
        'on-secondary-fixed': '#001a40',
        'on-tertiary-container': '#6c4b00',
        'error-container': '#93000a',
        'on-background': '#d9e2fd',
        'on-error': '#690005',
        'surface-bright': '#30394e',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#d9e2fd',
        'tertiary-container': '#fcb927',
        'on-surface': '#d9e2fd',
        'inverse-on-surface': '#273045',
        'on-tertiary-fixed-variant': '#5e4200',
        'on-primary': '#3e2e00',
        primary: '#ffdd8d',
        'on-secondary-fixed-variant': '#2e4672',
        'secondary-fixed': '#d7e2ff',
        tertiary: '#ffdca1',
        'on-primary-container': '#664e00',
        'secondary-fixed-dim': '#afc7fa',
        'on-primary-fixed': '#251a00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
